version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/algasamga
      - SPRING_DATASOURCE_USERNAME=XXXXXXXXX
      - SPRING_DATASOURCE_PASSWORD=XXXXXXXXX
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - BOT_TOKEN_API=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


  db:
    image: 'postgres:15-alpine'
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=XXXXXXXXXXX
      - POSTGRES_PASSWORD=XXXXXXXXXXXX
      - POSTGRES_DB=XXXXXXXXXXXX
    restart: unless-stopped

volumes:
  db_data: